% auto-generated by conn_jobmanager
% this script can be used to run this process from Matlab locally on this machine (or in a Matlab parallel toolbox environment)

addpath 'D:\matlabTools\spm12';
addpath 'D:\matlabTools\conn';
cd 'F:\fMRI1500\Conn\conn_fMRI1500.qlog\200621224559386';

jobs={'F:\fMRI1500\Conn\conn_fMRI1500.qlog\200621224559386\node.0001200621224559386.mat','F:\fMRI1500\Conn\conn_fMRI1500.qlog\200621224559386\node.0002200621224559386.mat','F:\fMRI1500\Conn\conn_fMRI1500.qlog\200621224559386\node.0003200621224559386.mat','F:\fMRI1500\Conn\conn_fMRI1500.qlog\200621224559386\node.0004200621224559386.mat','F:\fMRI1500\Conn\conn_fMRI1500.qlog\200621224559386\node.0005200621224559386.mat','F:\fMRI1500\Conn\conn_fMRI1500.qlog\200621224559386\node.0006200621224559386.mat'};
% runs individual jobs
parfor n=1:numel(jobs)
  conn_jobmanager('exec',jobs{n});
end

% merges job outputs with conn project
conn load 'F:\fMRI1500\Conn\conn_fMRI1500.mat';
conn save;
